### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by amiralipour** [l3p-cv/lost#36]
Hey 
I am trying to make a kubernetes deployment of the tool. So far all of the services and deployments seem to be working fine except the "lost-cv-0" which keeps crashing with following error:

Traceback (most recent call last): File "/opt/conda/envs/lost/bin/celery", line 11, in <module> sys.exit(main()) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/__main__.py", line 16, in main _main() File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main cmd.execute_from_commandline(argv) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline super(CeleryCommand, self).execute_from_commandline(argv))) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 273, in execute_from_commandline argv = self.setup_app_from_commandline(argv) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline self.app = self.find_app(app) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 501, in find_app return find_app(app, symbol_by_name=self.symbol_by_name) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/app/utils.py", line 359, in find_app sym = symbol_by_name(app, imp=imp) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 504, in symbol_by_name return imports.symbol_by_name(name, imp=imp) File "/opt/conda/envs/lost/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name module = imp(module_name, package=package, **kwargs) File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/utils/imports.py", line 104, in import_from_cwd return imp(module, package=package) File "/opt/conda/envs/lost/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1006, in _gcd_import File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 677, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 728, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/code/backend/lost/flaskapp.py", line 12, in <module> file_handler = FileHandler(os.path.join(settings.LOST_CONFIG.project_path,'logs','flask.log')) File "/opt/conda/envs/lost/lib/python3.7/logging/__init__.py", line 1041, in __init__ StreamHandler.__init__(self, self._open()) File "/opt/conda/envs/lost/lib/python3.7/logging/__init__.py", line 1070, in _open return open(self.baseFilename, self.mode, encoding=self.encoding) FileNotFoundError: [Errno 2] No such file or directory: '/home/lost/logs/flask.log'

I tried creating the logs directory manually but it didn't solve.

**Comment by gereonreus** [comment]
Hello amiralipour !

First we have to admit that we haven't tested the deployment with Kubernetes yet. 

However, it looks like the lost-cv-0 container has no access to the LOST_HOME directory. 
This can have several causes:

1. was the .env file correctly included ? 
2. is it possible that the lost-cv-0 container is executed on another node ? In this case LOST_HOME must also be made available for this node e.g. by nfs mounting.

Best regards,
Gereon
