### ISSUE TITLE
cannot delete user

### ISSUE THREAD

**Issue by xinyi61** [l3p-cv/lost#52]
**Describe the bug**

**To Reproduce**
1.Users    and a group, ex mygroup
2.add two users, named user1 、user2, and belong to mygroup
3. start pipeline, create two annotation task
4. delete pipeline when user1 user2 cannot finish annotation task
5. click Users  to delete user1 user2, cannot delete(an unexpected error has occured)
cat flask.log:
Traceback (most recent call last):
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/code/backend/lost/api/user/endpoint.py", line 132, in delete
    dbm.commit()
  File "/code/backend/lost/db/access.py", line 82, in commit
    self.session.commit()
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2381, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2345, in _flush
    flush_context.execute()
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 597, in execute
    uow
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 265, in delete_obj
    cached_connections, mapper, table, delete)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1028, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/conda/envs/lost/lib/python3.7/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`lost`.`anno_task`, CONSTRAINT `fk_anno_task_group_id_group` FOREIGN KEY (`group_id`) REFERENCES `group` (`idx`))') [SQL: 'DELETE FROM `group` WHERE `group`.idx = %s'] [parameters: (12,)] (Background on this error at: http://sqlalche.me/e/gkpj)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gereonreus** [comment]
Hello xinyi61 ,

I have a few more questions in order to understand the bug:
1. in the annotation task, was the user or group in which the user is included selected ?
2. has the user already done some annotations ?

Thanks,
Gereon

**Comment by xinyi61** [comment]
> 1. in the annotation task, was the user or group in which the user is included selected ?
    yes， both selected
> 2. has the user already done some annotations ?
   user1 do some annotations,but not finish

**Comment by gereonreus** [comment]
Hi,

As soon as a user has already made annotations, he can no longer be deleted. 
In this case it would not be possible to find out which user has made which annotation. Alternatively, all his annotations would have to be deleted.
This is of course a design question and can be further thought through. So far, however, we thought the current implementation made sense.
However, there is no feedback to the user, which is the reason why the deletion process failed. We should improve this !

However, this does not seem to be the reason for your error.

From your flask.log file you can see that it was not possible to delete a group the user belongs to due to a foreign key constraint.
In our implementation the user management was implemented as follows:
When a user is created, a user_default_group is immediately created for him, to which no other user can be added. This group is therefore not visible in user management.
If a user is deleted, his default group will be deleted first. This failed in your case.
Why was it implemented like this ?
This is because annotation tasks can only be assigned to one group at a time. 
So if you assign an AnnotationTask to only one user, you actually assign a group (from the point of view of the database), which is the group that represents the user default group of the single user. 

This means 
Probably you have selected user2 in one of your annotation tasks. 
Now, when trying to delete this user, the user_default_group will be deleted, which is connected to the AnnotationTask via a foreign key. This fails.
But also here a reasonable feedback about the reason of the failure in the user interface should appear as error message.
